package dialect

type KeywordKind int

//go:generate stringer -type KeywordKind kind.go
const (
	// Matched keyword
	Matched KeywordKind = iota
	// Data Manipulation Language
	DML
	// Data Definition Language
	DDL
	// Data Control Language
	DCL
	// Unmatched keyword (like table and column identifier)
	Unmatched = 99
)

// T-SQL keyword classification map.
var match = map[string]KeywordKind{
	// DML
	"SELECT":   DML,
	"INSERT":   DML,
	"UPDATE":   DML,
	"DELETE":   DML,
	"MERGE":    DML,
	"COMMIT":   DML,
	"ROLLBACK": DML,
	"TRUNCATE": DML,
	"BULK":     DML,

	// DDL
	"CREATE": DDL,
	"ALTER":  DDL,
	"DROP":   DDL,

	// DCL
	"GRANT":  DCL,
	"DENY":   DCL,
	"REVOKE": DCL,

	// Standard SQL keywords (matched)
	"ABS":               Matched,
	"ADD":               Matched,
	"ALL":               Matched,
	"AND":               Matched,
	"ANY":               Matched,
	"APPLY":             Matched,
	"AS":                Matched,
	"ASC":               Matched,
	"AT":                Matched,
	"AUTHORIZATION":     Matched,
	"AVG":               Matched,
	"BACKUP":            Matched,
	"BEGIN":             Matched,
	"BETWEEN":           Matched,
	"BIGINT":            Matched,
	"BINARY":            Matched,
	"BIT":               Matched,
	"BREAK":             Matched,
	"BROWSE":            Matched,
	"BY":                Matched,
	"CASCADE":           Matched,
	"CASE":              Matched,
	"CAST":              Matched,
	"CATCH":             Matched,
	"CEILING":           Matched,
	"CHAR":              Matched,
	"CHAR_LENGTH":       Matched,
	"CHARACTER":         Matched,
	"CHARACTER_LENGTH":  Matched,
	"CHECK":             Matched,
	"CHECKPOINT":        Matched,
	"CLOSE":             Matched,
	"CLUSTERED":         Matched,
	"COALESCE":          Matched,
	"COLLATE":           Matched,
	"COLUMN":            Matched,
	"COMPUTE":           Matched,
	"CONSTRAINT":        Matched,
	"CONTAINS":          Matched,
	"CONTAINSTABLE":     Matched,
	"CONTINUE":          Matched,
	"CONVERT":           Matched,
	"COUNT":             Matched,
	"COUNT_BIG":         Matched,
	"CROSS":             Matched,
	"CUME_DIST":         Matched,
	"CURRENT":           Matched,
	"CURRENT_DATE":      Matched,
	"CURRENT_TIME":      Matched,
	"CURRENT_TIMESTAMP": Matched,
	"CURRENT_USER":      Matched,
	"CURSOR":            Matched,
	"DATABASE":          Matched,
	"DATE":              Matched,
	"DATETIME":          Matched,
	"DATETIME2":         Matched,
	"DATETIMEOFFSET":    Matched,
	"DAY":               Matched,
	"DBCC":              Matched,
	"DEALLOCATE":        Matched,
	"DEC":               Matched,
	"DECIMAL":           Matched,
	"DECLARE":           Matched,
	"DEFAULT":           Matched,
	"DENSE_RANK":        Matched,
	"DESC":              Matched,
	"DISK":              Matched,
	"DISTINCT":          Matched,
	"DISTRIBUTED":       Matched,
	"DOUBLE":            Matched,
	"DUMP":              Matched,
	"ELSE":              Matched,
	"END":               Matched,
	"ERRLVL":            Matched,
	"ESCAPE":            Matched,
	"EXCEPT":            Matched,
	"EXEC":              Matched,
	"EXECUTE":           Matched,
	"EXISTS":            Matched,
	"EXIT":              Matched,
	"EXP":               Matched,
	"EXTERNAL":          Matched,
	"FETCH":             Matched,
	"FILE":              Matched,
	"FILLFACTOR":        Matched,
	"FIRST_VALUE":       Matched,
	"FLOAT":             Matched,
	"FLOOR":             Matched,
	"FOLLOWING":         Matched,
	"FOR":               Matched,
	"FOREIGN":           Matched,
	"FREETEXT":          Matched,
	"FREETEXTTABLE":     Matched,
	"FROM":              Matched,
	"FULL":              Matched,
	"FUNCTION":          Matched,
	"GLOBAL":            Matched,
	"GOTO":              Matched,
	"GROUP":             Matched,
	"GROUPING":          Matched,
	"HAVING":            Matched,
	"HOLDLOCK":          Matched,
	"HOUR":              Matched,
	"IDENTITY":          Matched,
	"IDENTITYCOL":       Matched,
	"IDENTITY_INSERT":   Matched,
	"IF":                Matched,
	"IMAGE":             Matched,
	"IN":                Matched,
	"INDEX":             Matched,
	"INNER":             Matched,
	"INT":               Matched,
	"INTEGER":           Matched,
	"INTERSECT":         Matched,
	"INTO":              Matched,
	"IS":                Matched,
	"JOIN":              Matched,
	"KEY":               Matched,
	"KILL":              Matched,
	"LAG":               Matched,
	"LAST_VALUE":        Matched,
	"LEAD":              Matched,
	"LEFT":              Matched,
	"LIKE":              Matched,
	"LINENO":            Matched,
	"LOAD":              Matched,
	"LOCAL":             Matched,
	"LOWER":             Matched,
	"MAX":               Matched,
	"MIN":               Matched,
	"MINUTE":            Matched,
	"MONEY":             Matched,
	"MONTH":             Matched,
	"NATIONAL":          Matched,
	"NCHAR":             Matched,
	"NOCHECK":           Matched,
	"NONCLUSTERED":      Matched,
	"NOT":               Matched,
	"NTH_VALUE":         Matched,
	"NTILE":             Matched,
	"NTEXT":             Matched,
	"NULL":              Matched,
	"NULLIF":            Matched,
	"NUMERIC":           Matched,
	"NVARCHAR":          Matched,
	"OF":                Matched,
	"OFF":               Matched,
	"OFFSET":            Matched,
	"OFFSETS":           Matched,
	"ON":                Matched,
	"OPEN":              Matched,
	"OPENDATASOURCE":    Matched,
	"OPENQUERY":         Matched,
	"OPENROWSET":        Matched,
	"OPENXML":           Matched,
	"OPTION":            Matched,
	"OR":                Matched,
	"ORDER":             Matched,
	"OUT":               Matched,
	"OUTER":             Matched,
	"OUTPUT":            Matched,
	"OVER":              Matched,
	"PARTITION":         Matched,
	"PERCENT":           Matched,
	"PERCENT_RANK":      Matched,
	"PERCENTILE_CONT":   Matched,
	"PERCENTILE_DISC":   Matched,
	"PIVOT":             Matched,
	"PLAN":              Matched,
	"POWER":             Matched,
	"PRECEDING":         Matched,
	"PRECISION":         Matched,
	"PRIMARY":           Matched,
	"PRINT":             Matched,
	"PROC":              Matched,
	"PROCEDURE":         Matched,
	"PUBLIC":            Matched,
	"RAISERROR":         Matched,
	"RANGE":             Matched,
	"RANK":              Matched,
	"READ":              Matched,
	"READTEXT":          Matched,
	"REAL":              Matched,
	"RECONFIGURE":       Matched,
	"REFERENCES":        Matched,
	"REPLICATION":       Matched,
	"RESTORE":           Matched,
	"RESTRICT":          Matched,
	"RETURN":            Matched,
	"RETURNS":           Matched,
	"REVERT":            Matched,
	"RIGHT":             Matched,
	"ROLLUP":            Matched,
	"ROW":               Matched,
	"ROW_NUMBER":        Matched,
	"ROWCOUNT":          Matched,
	"ROWGUIDCOL":        Matched,
	"ROWS":              Matched,
	"RULE":              Matched,
	"SAVE":              Matched,
	"SCHEMA":            Matched,
	"SECOND":            Matched,
	"SECURITYAUDIT":     Matched,
	"SESSION_USER":      Matched,
	"SET":               Matched,
	"SETUSER":           Matched,
	"SHUTDOWN":          Matched,
	"SMALLDATETIME":     Matched,
	"SMALLINT":          Matched,
	"SMALLMONEY":        Matched,
	"SOME":              Matched,
	"SQRT":              Matched,
	"SQL_VARIANT":       Matched,
	"STATISTICS":        Matched,
	"SUBSTRING":         Matched,
	"SUM":               Matched,
	"SYSTEM_USER":       Matched,
	"TABLE":             Matched,
	"TABLESAMPLE":       Matched,
	"TEXT":              Matched,
	"TEXTSIZE":          Matched,
	"THEN":              Matched,
	"THROW":             Matched,
	"TIME":              Matched,
	"TIMESTAMP":         Matched,
	"TINYINT":           Matched,
	"TO":                Matched,
	"TOP":               Matched,
	"TRAN":              Matched,
	"TRANSACTION":       Matched,
	"TRIGGER":           Matched,
	"TRIM":              Matched,
	"TRY":               Matched,
	"TRY_CAST":          Matched,
	"TRY_CONVERT":       Matched,
	"TRY_PARSE":         Matched,
	"TSEQUAL":           Matched,
	"UNBOUNDED":         Matched,
	"UNION":             Matched,
	"UNIQUE":            Matched,
	"UNIQUEIDENTIFIER":  Matched,
	"UNPIVOT":           Matched,
	"UPPER":             Matched,
	"USE":               Matched,
	"USER":              Matched,
	"USING":             Matched,
	"VALUES":            Matched,
	"VARBINARY":         Matched,
	"VARCHAR":           Matched,
	"VARYING":           Matched,
	"VIEW":              Matched,
	"WAITFOR":           Matched,
	"WHEN":              Matched,
	"WHERE":             Matched,
	"WHILE":             Matched,
	"WINDOW":            Matched,
	"WITH":              Matched,
	"WITHIN":            Matched,
	"WITHOUT":           Matched,
	"WRITETEXT":         Matched,
	"XML":               Matched,
	"YEAR":              Matched,
	"ZONE":              Matched,
}

func MatchKeyword(upperWord string) KeywordKind {
	kind, ok := match[upperWord]
	if !ok {
		return Unmatched
	}
	return kind
}

type DatabaseDriver string

const (
	DatabaseDriverMssql DatabaseDriver = "mssql"
)

func DataBaseKeywords(driver DatabaseDriver) []string {
	return mssqlKeywords
}

func DataBaseFunctions(driver DatabaseDriver) []string {
	return mssqlFunctions
}
